Assignment 11

Problem 1

In [1]:
import nltk
import re
#nltk.download('stopwords')
#nltk.download('gutenberg')
from nltk.corpus import gutenberg, stopwords
Stop_words = stopwords.words('english')
Sentences = gutenberg.sents('carroll-alice.txt')
TermsSentences = []
for terms in Sentences:
    terms = [w for w in terms if w not in Stop_words and w.lower() != 'said']
    terms = [w for w in terms if re.search(r'^[a-zA-Z]{2}', w) is not None]
    TermsSentences.append(terms)

In [2]:
TermsSentences[0:5]

[['Alice', 'Adventures', 'Wonderland', 'Lewis', 'Carroll'],
 ['CHAPTER'],
 ['Down', 'Rabbit', 'Hole'],
 ['Alice',
  'beginning',
  'get',
  'tired',
  'sitting',
  'sister',
  'bank',
  'nothing',
  'twice',
  'peeped',
  'book',
  'sister',
  'reading',
  'pictures',
  'conversations',
  'use',
  'book',
  'thought',
  'Alice',
  'without',
  'pictures',
  'conversation'],
 ['So',
  'considering',
  'mind',
  'well',
  'could',
  'hot',
  'day',
  'made',
  'feel',
  'sleepy',
  'stupid',
  'whether',
  'pleasure',
  'making',
  'daisy',
  'chain',
  'would',
  'worth',
  'trouble',
  'getting',
  'picking',
  'daisies',
  'suddenly',
  'White',
  'Rabbit',
  'pink',
  'eyes',
  'ran',
  'close']]

In [3]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [4]:
te = TransactionEncoder()
te_ary = te.fit(TermsSentences).transform(TermsSentences)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

,ALICE,ALL,AND,ARE,AT,Ada,Adventures,Advice,After,Ah,...,years,yelled,yelp,yer,yes,yesterday,yet,young,youth,zigzag
0,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1698,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1699,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1700,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1701,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1702,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False

In [5]:
frequent_itemsets = apriori(df, min_support=0.01, use_colnames=True)

In [6]:
frequent_itemsets

      support         itemsets
0    0.227246          (Alice)
1    0.038168            (And)
2    0.021726            (But)
3    0.015267            (Cat)
4    0.015267    (Caterpillar)
..        ...              ...
143  0.015854    (went, Alice)
144  0.014093   (Alice, would)
145  0.017616    (March, Hare)
146  0.032883   (Turtle, Mock)
147  0.012918  (Rabbit, White)

[148 rows x 2 columns]

In [7]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.5)

In [8]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(looked),(Alice),0.025250,0.227246,0.013506,0.534884,2.353765,1.0,0.007768,1.661421,0.590047,0.056511,0.398106,0.297158
1,(much),(Alice),0.029360,0.227246,0.016442,0.560000,2.464289,1.0,0.009770,1.756259,0.612177,0.068460,0.430608,0.316176
2,(quite),(Alice),0.028186,0.227246,0.014093,0.500000,2.200258,1.0,0.007688,1.545508,0.561329,0.058394,0.352964,0.281008
3,(thought),(Alice),0.043453,0.227246,0.034058,0.783784,3.449054,1.0,0.024183,3.573987,0.742321,0.143921,0.720200,0.466827
4,(March),(Hare),0.018203,0.017616,0.017616,0.967742,54.935484,1.0,0.017295,30.453905,1.000000,0.967742,0.967163,0.983871
5,(Hare),(March),0.017616,0.018203,0.017616,1.000000,54.935484,1.0,0.017295,inf,0.999402,0.967742,1.000000,0.983871
6,(Turtle),(Mock),0.034058,0.032883,0.032883,0.965517,29.362069,1.0,0.031763,28.046389,1.000000,0.965517,0.964345,0.982759
7,(Mock),(Turtle),0.032883,0.034058,0.032883,1.000000,29.362069,1.0,0.031763,inf,0.998786,0.965517,1.000000,0.982759
8,(Rabbit),(White),0.025250,0.012918,0.012918,0.511628,39.604651,1.0,0.012592,2.021167,1.000000,0.511628,0.505236,0.755814
9,(White),(Rabbit),0.012918,0.025250,0.012918,1.000000,39.604651,1.0,0.012592,inf,0.987507,0.511628,1.000000,0.755814

I used mlxtend with their apriori library to find the association rules. With the code provided to get the terms, I also decided to remove the word 'said' as well because it seemed to appear a lot in the rules. In the end, I found that the key phrases that remained were 'Mock Turtle' 'White Rabbit' and 'March Hare'.

Problem 2

In [9]:
def load_mnist(path, kind='train'):
    from numpy import fromfile, uint8
    import os
    import struct
    
    labels_path = os.path.join(path, '%s-labels-idx1-ubyte' % kind)
    images_path = os.path.join(path, '%s-images-idx3-ubyte' % kind)
    with open(labels_path, 'rb') as lbpath:
        magic, n = struct.unpack('>II', lbpath.read(8))
        labels = fromfile(lbpath, dtype=uint8)
        with open(images_path, 'rb') as imgpath:
            magic, num, rows, cols = struct.unpack(">IIII",imgpath.read(16))
            images = fromfile(imgpath, dtype=uint8).reshape(len(labels), 784)
            images = ((images / 255.) - .5) * 2
    return images, labels

X_train_mnist, y_train_mnist = load_mnist('EP_datasets/mnist/', kind='train')
print(f'Rows= {X_train_mnist.shape[0]}, columns= {X_train_mnist.shape[1]}')

X_test_mnist, y_test_mnist = load_mnist('EP_datasets/mnist/', kind='t10k')
print(f'Rows= {X_test_mnist.shape[0]}, columns= {X_test_mnist.shape[1]}')

Rows= 60000, columns= 784
Rows= 10000, columns= 784

In [10]:
import numpy as np
from sklearn.metrics import confusion_matrix
def get_acc(_y_test, _y_pred):
    return (np.sum(_y_test == _y_pred)).astype(float) / _y_test.shape[0]

In [11]:
class NeuralNetMLP(object):

    def __init__(self, n_hidden=30, n_hidden2=30, epochs=100, eta=0.001, minibatch_size=1, seed=None):
        self.random = np.random.RandomState(seed)  # used to randomize weights
        self.n_hidden = n_hidden  # size of the hidden layer
        self.n_hidden2 = n_hidden2  # new second hidden layer
        self.epochs = epochs  # number of iterations
        self.eta = eta  # learning rate
        self.minibatch_size = minibatch_size  # size of training batch - 1 would not work
        self.w_out, self.w_h = None, None
    
    @staticmethod
    def onehot(_y, _n_classes):  # one hot encode the input class y
        onehot = np.zeros((_n_classes, _y.shape[0]))
        for idx, val in enumerate(_y.astype(int)):
            onehot[val, idx] = 1.0
        return onehot.T
    
    @staticmethod
    def sigmoid(_z):  # Eq 1
        return 1.0 / (1.0 + np.exp(-np.clip(_z, -250, 250)))

    def _forward(self, _X):  # Eq 2
        z_h1 = np.dot(_X, self.w_h)
        a_h1 = self.sigmoid(z_h1)
        z_h2 = np.dot(a_h1, self.w_h2)  # new hidden layer
        a_h2 = self.sigmoid(z_h2)
        z_out = np.dot(a_h2, self.w_out)
        a_out = self.sigmoid(z_out)
        
        return z_h1, a_h1, z_h2, a_h2, z_out, a_out

    @staticmethod
    def compute_cost(y_enc, output):  # Eq 4
        term1 = -y_enc * (np.log(output))
        term2 = (1.0-y_enc) * np.log(1.0-output)
        cost = np.sum(term1 - term2)
        return cost

    def predict(self, _X):
        z_h1, a_h1, z_h2, a_h2, z_out, a_out = self._forward(_X)
        ypred = np.argmax(z_out, axis=1)
        return ypred

    def fit(self, _X_train, _y_train, _X_valid, _y_valid):
        import sys
        n_output = np.unique(_y_train).shape[0]  # number of class labels
        n_features = _X_train.shape[1]
        #self.w_out = self.random.normal(loc=0.0, scale=0.1, size=(self.n_hidden, n_output))
        self.w_h = self.random.normal(loc=0.0, scale=0.1, size=(n_features, self.n_hidden))
        self.w_h2 = self.random.normal(loc=0.0, scale=0.1, size=(self.n_hidden, self.n_hidden2))
        self.w_out = self.random.normal(loc=0.0, scale=0.1, size=(self.n_hidden2, n_output))

        y_train_enc = self.onehot(_y_train, n_output)  # one-hot encode original y
        for ei in range(self.epochs):  # Ideally must shuffle at every epoch
            indices = np.arange(_X_train.shape[0])
            for start_idx in range(0, indices.shape[0] - self.minibatch_size + 1, self.minibatch_size):
                batch_idx = indices[start_idx:start_idx + self.minibatch_size]
                
                z_h1, a_h1, z_h2, a_h2, z_out, a_out = self._forward(_X_train[batch_idx])  # neural network model
                
                delta_out = a_out - y_train_enc[batch_idx]
                sigmoid_derivative_h2 = a_h2 * (1.0 - a_h2)
                delta_h2 = np.dot(delta_out, self.w_out.T) * sigmoid_derivative_h2

                sigmoid_derivative_h1 = a_h1 * (1.0 - a_h1)
                delta_h1 = np.dot(delta_h2, self.w_h2.T) * sigmoid_derivative_h1

                grad_w_out = np.dot(a_h2.T, delta_out)
                grad_w_h2 = np.dot(a_h1.T, delta_h2)
                grad_w_h1 = np.dot(_X_train[batch_idx].T, delta_h1)
                
                self.w_out -= self.eta * grad_w_out
                self.w_h2 -= self.eta * grad_w_h2
                self.w_h -= self.eta * grad_w_h1
                

            # Evaluation after each epoch during training
            z_h1, a_h1, z_h2, a_h2, z_out, a_out = self._forward(_X_train)
            cost = self.compute_cost(y_enc=y_train_enc, output=a_out)
            y_train_pred = self.predict(_X_train)  # monitoring training progress through reclassification
            y_valid_pred = self.predict(_X_valid)  # monitoring training progress through validation
            train_acc = ((np.sum(_y_train == y_train_pred)).astype(float) / _X_train.shape[0])
            valid_acc = ((np.sum(_y_valid == y_valid_pred)).astype(float) / _X_valid.shape[0])
            sys.stderr.write('\r%d/%d | Cost: %.2f ' '| Train/Valid Acc.: %.2f%%/%.2f%% '%
                (ei+1, self.epochs, cost, train_acc*100, valid_acc*100))
            sys.stderr.flush()
        return self

In [12]:
# Define and fit the neural network
nn = NeuralNetMLP(n_hidden=20, n_hidden2=20, epochs=100, eta=0.0005, minibatch_size=100, seed=1)

nn.fit(X_train_mnist[:55000], y_train_mnist[:55000], X_train_mnist[55000:], y_train_mnist[55000:]) ;

100/100 | Cost: 13014.03 | Train/Valid Acc.: 96.73%/96.00%

In [13]:
y_pred = nn.predict(X_test_mnist)

print(f'Accuracy= {get_acc(y_test_mnist, y_pred)*100:.2f}%')
print(confusion_matrix(y_test_mnist, y_pred))

Accuracy= 95.03%
[[ 957    0    1    2    1    4    4    5    6    0]
 [   0 1105    3    2    0    1    4    4   16    0]
 [  12    0  969   10    6    1    3   14   17    0]
 [   3    0   13  962    0   10    0   11    9    2]
 [   1    1    7    0  936    0    5    3    5   24]
 [   4    2    2   18    2  830    5    5   17    7]
 [  10    4    3    0    8   14  909    0   10    0]
 [   1    4   12    8    2    1    0  983    5   12]
 [   6    2    6    4    8   11    6   14  911    6]
 [   3    4    0    6   24   10    2   11    8  941]]